In [1]:
import numpy as np

def sigmoid(a):
        return 1 / (1 + np.exp(-a))
    
x1 = np.array([[1], [2]])
w1 = np.array([[0.4, 0.3], [0.7, 0.6]])
a1 = w1.dot(x1)

x2 = sigmoid(a1)
w2 = np.array([[0.2, 0.3], [1, 0.7]])
a2 = w2.dot(x2)

y = sigmoid(a2)
y

array([[0.60041131],
       [0.79248709]])

In [2]:
import numpy as np

def sigmoid(a):
        return 1 / (1 + np.exp(-a))

x1 = np.array([[1], [2]])
w1 = np.array([[0.4, 0.3], [0.7, 0.6]])
a1 = w1.dot(x1)

x2 = sigmoid(a1)
w2 = np.array([[0.2, 0.3], [1, 0.7]])
a2 = w2.dot(x2)

y = sigmoid(a2)
t = np.array([[1], [0]])
print(y)

X = [x1, x2]
A = [a1, a2]
W = [w1, w2]

max_layer = len(X)

def f(a):
        return (1 - sigmoid(a)) * sigmoid(a)
    
def g(l, j):
        if max_layer == l:
                return (y[j] - t[j]) * f(A[l - 1][j])
        else:
                output = 0
                m = A[l - 1].shape[0]
                for i in range(m):
                    output += g(l + 1, i) * W[l][j, i] * f(A[l - 1][j])
                return output

def diff(j, k, l):
        return g(l, j) * X[l - 1][k]

for _ in range(100):
        for l in range(len(X)):
            for j in range(W[l].shape[0]):
                for k in range(W[l].shape[1]):
                    W[l][j, k] = W[l][j, k] -diff(j, k, l + 1)
        A[0] = W[0].dot(X[0])
        X[1] = sigmoid(A[0])
        A[1] = W[1].dot(X[1])
        y = sigmoid(A[1])

print(y)

[[0.60041131]
 [0.79248709]]
[[0.91175343]
 [0.08878309]]


In [3]:
import numpy as np

def sigmoid(a):
        return 1 / (1 + np.exp(-a))

x1 = np.array([[1], [2]])
w1 = np.array([[0.4, 0.3], [0.7, 0.6]])
b1 = np.array([[1.0], [1.0]])
a1 = w1.dot(x1) + b1

x2 = sigmoid(a1)
w2 = np.array([[0.2, 0.3], [1, 0.7]])
b2 = np.array([[1.0], [1.0]])
a2 = w2.dot(x2) + b2

y = sigmoid(a2)
t = np.array([[1], [0]])
print(y)

X = [x1, x2]
A = [a1, a2]
W = [w1, w2]
B = [b1, b2]

max_layer = len(X)

def f(a):
        return (1 - sigmoid(a)) * sigmoid(a)
    
def g(l, j):
        if max_layer == l:
                return (y[j] - t[j]) * f(A[l - 1][j])
        else:
                output = 0
                m = A[l - 1].shape[0]
                for i in range(m):
                    output += g(l + 1, i) * W[l][j, i] * f(A[l - 1][j])
                return output

def diff_w(j, k, l):
        return g(l, j) * X[l - 1][k]

def diff_b(j, l):
        return g(l, j)

for _ in range(100):
        for l in range(len(X)):
            for j in range(W[l].shape[0]):
                for k in range(W[l].shape[1]):
                    W[l][j, k] = W[l][j, k] -diff_w(j, k, l + 1)
                B[l][j] = B[l][j] - diff_b(j, l + 1)
        A[0] = W[0].dot(X[0]) + B[0]
        X[1] = sigmoid(A[0])
        A[1] = W[1].dot(X[1]) + B[1]
        y = sigmoid(A[1])

print(y)
print(w1)
print(w2)
print(b1)
print(b2)

[[0.81161118]
 [0.92718895]]
[[0.95372997]
 [0.05072232]]
[[0.29944487 0.09888974]
 [0.72157356 0.64314712]]
[[ 0.71255908  0.88221297]
 [-0.7731857  -1.2797488 ]]
[[0.89944487]
 [1.02157356]]
[[ 1.61312855]
 [-1.08877213]]


In [7]:
import numpy as np

def sigmoid(a):
        return 1 / (1 + np.exp(-a))

def f(a):
        return(1 - sigmoid(a)) * sigmoid(a)
    
def g(l, j):
        if max_layer == l:
                return (y[j] - t[j]) * W[l][i, j] * f(A[l - 1][j])
        else:
                output = 0
                m = A[l].shape[0]
                for i in range(m):
                        output += g(l + 1, i) * W[l][i, j] * f(A[l - 1][j])
                return output
import numpy as np

# シグモイド関数の定義
def sigmoid(a):
    return 1 / (1 + np.exp(-a))

# 活性化関数の微分
def f(a):
    return (1 - sigmoid(a)) * sigmoid(a)

# 更新式の公式gの実装
def g(l, j):
    if max_layer == l:
        return (y[j] - t[j]) * f(A[l - 1][j])
    else:
        output = 0
        m = A[l].shape[0]
        for i in range(m):
            output += g(l + 1, i) * W[l][i, j] * f(A[l - 1][j])
        return output

# パラメーターwによる誤差関数の微分
def diff_w(j, k, l):
    return g(l, j) * X[l - 1][k]

# パラメーターbによる誤差関数の微分
def diff_b(j, l):
    return g(l, j)


# Wの定義
w1 = np.random.normal(0.0, 1.0, (10, 784))
w2 = np.random.normal(0.0, 1.0, (2, 10))
W = [w1, w2]

# Bの定義
b1 = np.ones((10, 1))
b2 = np.ones((2, 1))
B = [b1, b2]

# 13007個中のデータから前100個のデータの読み込む
xs = np.load('Bambi_Virgo01/section4-4/inputs.npy')[0:101]
ts = np.load('Bambi_Virgo01/section4-4/true_values.npy')[0:101]

# x, tを一緒にループさせる
for x, t in zip(xs, ts):
    # 一層目
    x1 = x.flatten().reshape(784, 1)
    a1 = W[0].dot(x1) + b1

    # 二層目
    x2 = sigmoid(a1)
    a2 = W[1].dot(x2) + b2

    # 出力値と正解値
    y = sigmoid(a2)
    if np.argmax(y) == np.argmax(t):
        print("正解")
    else:
        print("不正解")

    # パラメーターの更新に使うためx,aをリスト化
    X = [x1, x2]
    A = [a1, a2]

    # パラメーターが何層あるかのサイズの取得
    max_layer = len(X)

    # パラメーターw, bの更新
    for l in range(len(X)):
        for j in range(W[l].shape[0]):
            for k in range(W[l].shape[1]):
                W[l][j, k] = W[l][j, k] - diff_w(j, k, l + 1)
            B[l][j] = B[l][j] - diff_b(j, l + 1)

np.save("w1.npy", W[0])
np.save("w2.npy", W[1])
np.save("b1.npy", B[0])
np.save("b2.npy", B[1])

正解
正解
正解
正解
不正解
正解
正解
不正解
不正解
正解
不正解
不正解
正解
正解
正解
不正解
正解
正解
正解
不正解
不正解
不正解
正解
不正解
正解
正解
不正解
不正解
正解
正解
正解
不正解
正解
正解
正解
不正解
不正解
正解
正解
不正解
正解
不正解
不正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
不正解
正解
正解
不正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
不正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解
正解


In [11]:
import numpy as np
import random

def sigmoid(a):
        return 1 / (1 + np.exp(-a))

for i in range(10):
        index = random.randint(0, 13007)
        
        x1 = np.load('Bambi_Virgo01/section4-3/xs.npy')[index].flatten().reshape(784, 1)
        w1 = np.load('w1.npy')
        w2 = np.load('w2.npy')
        b1 = np.load('b1.npy')
        b2 = np.load('b2.npy')
        
        a1 = w1.dot(x1) + b1
        x2 = sigmoid(a1)
        a2 = w2.dot(x2) + b2
        y = sigmoid(a2)
        t = np.load('Bambi_Virgo01/section4-3/ts.npy')[200]
        
        if np.argmax(y) == np.argmax(t):
                print("正解")
        else:
                print("不正解")

正解
不正解
不正解
不正解
不正解
正解
不正解
不正解
正解
不正解


In [12]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation
import numpy as np

xs = np.load('Bambi_Virgo01/section4-4/inputs.npy')
ts = np.load('Bambi_Virgo01/section4-4/true_values.npy')

model = Sequential()
model.add(Dense(units=10, input_shape=xs[0].shape))
model.add(Activation('sigmoid'))
model.add(Dense(units=2))
model.add(Activation('sigmoid'))

model.compile(loss='mean_squared_error',
                          optimizer='SGD')

model.fit(xs, ts, batch_size=1, verbose=1)

json_string = model.to_json()
open('Bambi_Virgo01/section4-4/model.json', 'w').write(json_string)
model.save_weights('model.h5')

Using TensorFlow backend.


Epoch 1/1
13007/13007 [==============================] - 31s 2ms/step - loss: 0.0461


In [15]:
import numpy as np
from keras.models import model_from_json

model = model_from_json(open('Bambi_Virgo01/section4-4/model.json').read())
model.load_weights('model.h5')

xs = np.load("Bambi_Virgo01/section4-4/inputs_for_validation.npy")
ts = np.load("Bambi_Virgo01/section4-4/true_values_for_validation.npy")

accuracy_count = 0

for x, t in zip(xs, ts):
        y = model.predict_classes(x.reshape(1, 784))
        if y == t:
                accuracy_count += 1

print("予測精度： ", accuracy_count / xs.shape[0])

予測精度：  0.984743411927878
