In [1]:
# 逆伝播

In [2]:
import numpy as np

In [3]:
y = np.array([1, 2, 3])

In [4]:
np.sum(y)

6

In [5]:
y = [1, 2, 3, 4, 5, 6, 7, 8, 9]
np.sum(y)

45

In [1]:
import numpy as np
y = np.array([0.8, 0.2])
t = np.array([1, 0])

def mean_squared_error(y, t):
    return 0.5 * np.sum((y-t)**2)

E = mean_squared_error(y, t)
E

0.039999999999999994

In [18]:
import numpy as np

def sigmoid(a):
    return 1 / (1 + np.exp(-a))

def mse(y, t):
    return 0.5 * (np.sum(y-t)**2)

w = np.array([[0.1]])
x = np.array([[3]])
t = np.array([1])

a = w.dot(x)
y = sigmoid(a)
E = mse(y, t)

In [19]:
y

array([[0.57444252]])

In [20]:
E

0.09054958574879755

In [21]:
def diff(y, a, x):
    return (y-1)*(1-sigmoid(a))*sigmoid(a)*x

In [26]:
for _ in range(100):
    w = w - diff(y, a, x)
    a = w.dot(x)
    y = sigmoid(a)
    E = mse(y, t)

In [27]:
y

array([[0.97572733]])

In [28]:
E

0.0002945812485453371

In [29]:
import numpy as np

def sigmoid(a):
    return 1 / (1 + np.exp(-a))

def mse(y, t):
    return 0.5 * (np.sum((y-t) ** 2))

In [30]:
w = np.array([[0.3, 0.4], [0.7, 0.9]])
x = np.array([[2], [1]])
t = np.array([[1], [0]])

In [31]:
a = w.dot(x)
y = sigmoid(a)
E = mse(y, t)

In [32]:
y

array([[0.73105858],
       [0.90887704]])

In [33]:
E

0.44919348006145793

In [35]:
def diff(y, t, a, x):
    return ((y-t) * (1-sigmoid(a))*(sigmoid(a))).dot(x.T)

In [36]:
w = w - diff(y, t, a, x)

In [37]:
w

array([[0.40575419, 0.45287709],
       [0.54945439, 0.8247272 ]])

In [38]:
a = w.dot(x)
y = sigmoid(a)
E = mse(y, t)

In [39]:
y

array([[0.77978012],
       [0.87254335]])

In [40]:
E

0.4049143428617733

In [41]:
for _ in range(100):
    w = w -diff(y, t, a, x)
    a = w.dot(x)
    y = sigmoid(a)

E = mse(y, t)

In [42]:
w

array([[ 1.25203093,  0.87601546],
       [-1.55891013, -0.22945507]])

In [43]:
y

array([[0.96707607],
       [0.0339845 ]])

In [44]:
E

0.0011194658168959491