In [3]:
import numpy as np
def sigmoid(a):
    return 1 / (1 + np.exp(-a))

x1 = np.array([[1], [2]])
w1 = np.array([[0.4, 0.3], [0.7, 0.6]])
a1 = w1.dot(x1)
x2 = sigmoid(a1)
w2 = np.array([[0.2, 0.3], [1, 0.7]])
a2 = w2.dot(x2)
y = sigmoid(a2)
y

array([[0.60041131],
       [0.79248709]])

In [11]:
import numpy as np

# シグモイド関数の定義
def sigmoid(a):
    return 1 / (1 + np.exp(-a))


# 一層目
x1 = np.array([[1], [2]])
w1 = np.array([[0.4, 0.3], [0.7, 0.6]])
a1 = w1.dot(x1)

# 二層目
x2 = sigmoid(a1)
w2 = np.array([[0.2, 0.3], [1, 0.7]])
a2 = w2.dot(x2)

# 出力値と正解値
y = sigmoid(a2)
t = np.array([[1], [0]])
print(y)

# 入力値、パラメーター、合算値を配列化
X = [x1, x2]
A = [a1, a2]
W = [w1, w2]

# パラメーターが何層あるかのサイズの取得
max_layer = len(X)


# 活性化関数の微分
def f(a):
    return (1 - sigmoid(a)) * sigmoid(a)


# 更新式の公式gの実装
def g(l, j):
    if max_layer == l:
        return (y[j] - t[j]) * f(A[l - 1][j])
    else:
        output = 0
        m = A[l - 1].shape[0]
        for i in range(m):
            output += g(l + 1, i) * W[l][j, i] * f(A[l - 1][j])
        return output


# パラメーターwによる誤差関数の微分
def diff(j, k, l):
    return g(l, j) * X[l - 1][k]


# パラメーターを100回学習
for _ in range(100):
    for l in range(len(X)):
        for j in range(W[l].shape[0]):
            for k in range(W[l].shape[1]):
                W[l][j, k] = W[l][j, k] - diff(j, k, l + 1)
    A[0] = W[0].dot(X[0])
    X[1] = sigmoid(A[0])
    A[1] = W[1].dot(X[1])
    y = sigmoid(A[1])

print(y)

[[0.60041131]
 [0.79248709]]
[[0.91175343]
 [0.08878309]]


In [14]:
import numpy as np

# シグモイド関数の定義
def sigmoid(a):
    return 1 / (1 + np.exp(-a))

# 1層目
x1 = np.array([[1], [2]])
w1 = np.array([[0.4, 0.3], [0.7, 0.6]])
b1 = np.array([[1.0], [1.0]])
a1 = w1.dot(x1) + b1

# 2層目
x2 = sigmoid(a1)
w2 = np.array([[0.2, 0.3], [1, 0.7]])
b2 = np.array([[1.0], [1.0]])
a2 = w2.dot(x2) + b2

# 出力値と正解値
y = sigmoid(a2)
t = np.array([[1], [0]])
print(y)

# 入力値、パラメーター、合算値を配列化
X = [x1, x2]
A = [a1, a2]
W = [w1, w2]
B = [b1, b2]

# パラメータが何個あるかのサイズの取得
max_layer = len(X)

# 活性化関数の微分
def f(a):
    return(1 - sigmoid(a)) * sigmoid(a)

# 更新式の公式gの実装
def g(l, j):
    if max_layer == l:
        return (y[j] - t[j]) * f(A[l - 1][j])
    else:
        output = 0
        m = A[l - 1].shape[0]
        for i in range(m):
            output += g(l + 1, i) * W[l][j, i] * f(A[l - 1][j])
        return output
    
# パラメーターwによる誤差関数の微分
def diff_w(j, k, l):
    return g(l, j) * X[l - 1][k]

# パラメーターbにおける誤差関数の微分
def diff_b(j, l):
    return g(l, j)

for _ in range(100):
    for l in range(len(X)):
        for j in range(W[l].shape[0]):
            for k in range(W[l].shape[1]):
                W[l][j, k] = W[l][j, k] - diff_w(j, k, l + 1)
            B[l][j] = B[l][j] - diff_b(j, l + 1)
    A[0] = W[0].dot(X[0]) + B[0]
    X[1] = sigmoid(A[0])
    A[1] = W[1].dot(X[1]) + B[1]
    y = sigmoid(A[1])
    
print(y)
print(w1)
print(w2)
print(b1)
print(b2)

[[0.81161118]
 [0.92718895]]
[[0.95372997]
 [0.05072232]]
[[0.29944487 0.09888974]
 [0.72157356 0.64314712]]
[[ 0.71255908  0.88221297]
 [-0.7731857  -1.2797488 ]]
[[0.89944487]
 [1.02157356]]
[[ 1.61312855]
 [-1.08877213]]


In [2]:
import keras

In [3]:
from keras.models import Sequential
from keras.layers.core import Dense, Activation
import numpy as np

#1: 入力データと正解値の取得
xs = np.load('inputs.npy')
ts = np.load('true_values.npy')

#2: モデルと構築するために必要な情報を格納
model = Sequential()
model.add(Dense(units=10, input_shape=xs[0].shape))
model.add(Activation('sigmoid'))
model.add(Dense(units=2))
model.add(Activation('sigmoid'))

#3: モデルの構築
model.compile(loss='mean_squared_error',
                           optimizer='SGD')

#4: 構築したモデルに入力値と正解値を渡し、パラメーターの学習を開始
model.fit(xs, ts, batch_size=1, verbose=1)

#5: 学習結果の保存
json_string = model.to_json()
open('model.json', 'w').write(json_string)
model.save_weights('model.h5')

FileNotFoundError: [Errno 2] No such file or directory: 'inputs.npy'

In [ ]:
import numpy as np
from keras.models import model_from_json

#1: 構築したモデルの情報の取得
model = model_from_json(open('model.json').read())
model.load_weights('model.h5')

#2: テストデータの取得
xs = np.load("inputs_for_validation.npy")
ts = np.load("true_values_for_validation.npy")

#3: 予測に正解した数を保存する変数
accuracy_count = 0

#4: モデルの精度を判定する
for x, t in zip(xs, ts):
    y = model.predict_classes(x.reshape(1, 784))
    if y == t:
        accuracy_count += 1

#5: モデルの精度の結果を出力
print("予測精度；", accuracy_count / xs.shape[0])